### ISSUE TITLE
pibooth crash

### ISSUE THREAD

**Issue by arthur5640** [pibooth/pibooth#211]
hello, when i put on escape twice , i have the crash and i can't execute pibooth.
How i can resolve this:

**
 *                     Oops! It seems that pibooth has crached                     *
 *     You can report an issue on https://github.com/pibooth/pibooth/issues/new    *
 *                       and post the file: /tmp/pibooth.log                       *
 ***********************************************************************************
pi@raspberrypi:~ $ pibooth
pygame 2.0.1 (SDL 2.0.9, Python 3.7.3)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/usr/local/bin/pibooth", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/pibooth/booth.py", line 425, in main
    config = PiConfigParser("~/.config/pibooth/pibooth.cfg", plugin_manager)
  File "/usr/local/lib/python3.7/dist-packages/pibooth/config/parser.py", line 256, in __init__
    self.load()
  File "/usr/local/lib/python3.7/dist-packages/pibooth/config/parser.py", line 294, in load
    self.handle_autostart()
  File "/usr/local/lib/python3.7/dist-packages/pibooth/config/parser.py", line 308, in handle_autostart
    enable = self.getboolean('GENERAL', 'autostart')
  File "/usr/lib/python3.7/configparser.py", line 828, in getboolean
    raw=raw, vars=vars, fallback=fallback, **kwargs)
  File "/usr/lib/python3.7/configparser.py", line 808, in _get_conv
    **kwargs)
  File "/usr/lib/python3.7/configparser.py", line 802, in _get
    return conv(self.get(section, option, **kwargs))
  File "/usr/lib/python3.7/configparser.py", line 1160, in _convert_to_boolean
    raise ValueError('Not a boolean: %s' % value)
ValueError: Not a boolean: ('False',)
pi@raspberrypi:~ $

**Comment by arthur5640** [comment]
- [

1. 

- [ ] @

](url)
