### ISSUE TITLE
SDL2 error on touchscreen computer

### ISSUE THREAD

**Issue by sravel** [pibooth/pibooth#240]
**Describe the bug**
When I develop pibooth plugin and test some code modification I work on XPS13 computer
since last update, when I open Menu, the app close with this error:
```
  pibooth           : The get_cursor method is unavailable in SDL2
Traceback (most recent call last):
  File "/home/ravel/Téléchargements/pibooth-werdeil/pibooth/booth.py", line 375, in main_loop
    self._menu.process(events)
  File "/home/ravel/Téléchargements/pibooth-werdeil/pibooth/config/menu.py", line 345, in process
    self._main_menu.update(events)
  File "/usr/local/lib/python3.8/dist-packages/pygame_menu/menu.py", line 2590, in update
    widget._check_mouseover(event)
  File "/usr/local/lib/python3.8/dist-packages/pygame_menu/widgets/core/widget.py", line 679, in _check_mouseover
    self.mouseover(event, check_all_widget_mouseleave)
  File "/usr/local/lib/python3.8/dist-packages/pygame_menu/widgets/core/widget.py", line 600, in mouseover
    previous_cursor = pygame.mouse.get_cursor()  # Previous cursor
TypeError: The get_cursor method is unavailable in SDL2
[ ERROR   ] pibooth           : system='Linux', node='RAVEL', release='5.8.0-25-generic', version='#26-Ubuntu SMP Thu Oct 15 10:30:38 UTC 2020', machine='x86_64', processor='x86_64'
 ```

**Environment**
 - Ubuntu 20.04
 - Camera XPS13
 - Pibooth version master

**Comment by anxuae** [comment]
Hi @sravel , I have created an issue in `pygame-menu` library: #330

**Comment by anxuae** [comment]
Can you confirm me the version of **pygame** and **SDL2** you are using?
Currently on Windows, I have not this issue using with this config pygame 2.0.1 (SDL 2.0.14, Python 3.9.2).

You can try to update to the last SDL version (2.0.14) if you are on a lower version...

**Comment by sravel** [comment]
I use
**pygame 2.0.0 (SDL 2.0.12, python 3.8.6)**

but yes if update to 
**pygame 2.0.1 (SDL 2.0.14, Python 3.8.6)**
there is no bug.
Thanks a lot @anxuae
