### ISSUE TITLE
Add support for libcamera/picamera2 (PiOS bullseye and Arducam)

### ISSUE THREAD

**Issue by tityann** [pibooth/pibooth#290]
hello
Could someone add the support for the arducam pivariety camera please
this camera use libcamera to work. 
she is compatible with openCV
my imx298 modele : https://www.arducam.com/docs/cameras-for-raspberry-pi/pivariety/16mp-imx298-pivariety-motorized-focus-camera-module/
installation of librairie : https://www.arducam.com/docs/cameras-for-raspberry-pi/pivariety/how-to-access-and-program-the-pivariety-camera-using-command-line-python-opencv-and-gstreamer
thanks for the help

**Comment by tityann** [comment]
hello
could someone tell what i could do to help this issue.
i can't do it alone
i check the source but i can't identify when the probblem come

**Comment by anxuae** [comment]
If the Arducam works with OpenCV, you could create a plugin which give priority to OpenCV camera (and ignore Raspberrypi camera).
For instance, save this code in a file and setup it in th configuration file:

```python
"""Plugin to use OpenCV and gPhoto2 camera."""

import time
import pibooth
from pibooth.utils import LOGGER
from pibooth import camera

__version__ = "1.0.0"

@pibooth.hookimpl
def pibooth_setup_camera(cfg):
    cv_cam_proxy = camera.get_cv_camera_proxy()
    gp_cam_proxy = camera.get_gp_camera_proxy()

    if cv_cam_proxy and gp_cam_proxy:
        LOGGER.info("Configuring hybrid camera with retry (OpenCV + gPhoto2) ...")
        return camera.HybridCvCamera(cv_cam_proxy, gp_cam_proxy)
    elif gp_cam_proxy:
        LOGGER.info("Configuring gPhoto2 camera with retry ...")
        return camera.GpCamera(gp_cam_proxy)
    elif cv_cam_proxy:
        LOGGER.info("Configuring OpenCV camera ...")
        return camera.CvCamera(cv_cam_proxy)
```

**Comment by anxuae** [comment]
Can you give me the result of the following command:

```
vcgencmd get_camera
```

**Comment by tityann** [comment]
hello
thank you i will try it this evening
but before, could you explain me this
`For instance, save this code in a file and setup it in th configuration file:`
i just put the name of the file , i created in the configuration file ?
thanks

**Comment by anxuae** [comment]
If you want to learn about plugins, please have a look to the documentation: https://pibooth.readthedocs.io/en/latest/sources/plugins/plugins.html

In the configuration, you will find the key `[GENERAL][plugins]` where you can put the path the file of the custom plugin

**Comment by tityann** [comment]
hello
pi@raspberrypi:~ $ vcgencmd get_camera
supported=1 detected=0

**Comment by tityann** [comment]
for the plugins thanks..but i will try tomorow...
it seems that in my several test, i broke something because opencv doen't work anymore in my configuration

**Comment by anxuae** [comment]
Can you post the complete log file? I believe that error is coming from OpenCV library, but I need to be sure

**Comment by tityann** [comment]
unfortunatly, this is the only message...repeating on every line
in loop

**Comment by anxuae** [comment]
I missed `import libcamera` at the beginning of the plugin.
The comment is to indicate that you have to implement all the methods (using libcamera API of course) as it is done for OpenCV driver located in https://github.com/pibooth/pibooth/blob/master/pibooth/camera/opencv.py

**Comment by anxuae** [comment]
I've quickly made a draft of the driver class. But I can debug it. Now it's your job ;-)

```python

class LibcamCamera(BaseCamera):

    """Libcamera camera management.
    """

    IMAGE_EFFECTS = [u'none',
                     u'blur',
                     u'contour',
                     u'detail',
                     u'edge_enhance',
                     u'edge_enhance_more',
                     u'emboss',
                     u'find_edges',
                     u'smooth',
                     u'smooth_more',
                     u'sharpen']

    def __init__(self, camera_proxy):
        super(LibcamCamera, self).__init__(camera_proxy)
        self._overlay_alpha = 255

    def _specific_initialization(self):
        """Camera initialization.
        """
        self._cam.initCamera(self.resolution[0], self.resolution[1],
                             libcamera.PixelFormat.RGB888, buffercount=4,
                             rotation=self.preview_rotation)
        self._cam.set(libcamera.ExposureTime, self.preview_iso)

    def _show_overlay(self, text, alpha):
        """Add an image as an overlay.
        """
        if self._window:  # No window means no preview displayed
            rect = self.get_rect()
            self._overlay_alpha = alpha
            self._overlay = self.build_overlay((rect.width, rect.height), str(text), alpha)

    def _get_preview_image(self):
        """Capture a new preview image.
        """
        rect = self.get_rect()

        ret, data = self._cam.readFrame()
        if not ret:
            raise IOError("Can not get camera preview image")

        image = Image.open(io.BytesIO(data.imageData))
        self._cam.returnFrameBuffer(data)
        # Crop to keep aspect ratio of the resolution
        image = image.crop(sizing.new_size_by_croping_ratio(image.size, self.resolution))
        # Resize to fit the available space in the window
        image = image.resize(sizing.new_size_keep_aspect_ratio(image.size, (rect.width, rect.height), 'outer'))

        if self.preview_flip:
            image = image.transpose(Image.FLIP_LEFT_RIGHT)

        if self._overlay:
            image.paste(self._overlay, (0, 0), self._overlay)
        return image

    def _post_process_capture(self, capture_data):
        """Rework capture data.

        :param capture_data: couple (frame, effect)
        :type capture_data: tuple
        """
        frame, effect = capture_data
        image = Image.open(io.BytesIO(frame))

        # Crop to keep aspect ratio of the resolution
        image = image.crop(sizing.new_size_by_croping_ratio(image.size, self.resolution))
        # Resize to fit the resolution
        image = image.resize(sizing.new_size_keep_aspect_ratio(image.size, self.resolution, 'outer'))

        if self.capture_flip:
            image = image.transpose(Image.FLIP_LEFT_RIGHT)

        if effect != 'none':
            image = image.filter(getattr(ImageFilter, effect.upper()))

        return image

    def preview(self, window, flip=True):
        """Setup the preview.
        """
        self._window = window
        self.preview_flip = flip
        self._window.show_image(self._get_preview_image())

    def preview_countdown(self, timeout, alpha=80):
        """Show a countdown of `timeout` seconds on the preview.
        Returns when the countdown is finished.
        """
        timeout = int(timeout)
        if timeout < 1:
            raise ValueError("Start time shall be greater than 0")

        timer = PoolingTimer(timeout)
        while not timer.is_timeout():
            remaining = int(timer.remaining() + 1)
            if self._overlay is None or remaining != timeout:
                # Rebluid overlay only if remaining number has changed
                self._show_overlay(str(remaining), alpha)
                timeout = remaining

            updated_rect = self._window.show_image(self._get_preview_image())
            pygame.event.pump()
            if updated_rect:
                pygame.display.update(updated_rect)

        self._show_overlay(get_translated_text('smile'), alpha)
        self._window.show_image(self._get_preview_image())

    def preview_wait(self, timeout, alpha=80):
        """Wait the given time.
        """
        timeout = int(timeout)
        if timeout < 1:
            raise ValueError("Start time shall be greater than 0")

        timer = PoolingTimer(timeout)
        while not timer.is_timeout():
            updated_rect = self._window.show_image(self._get_preview_image())
            pygame.event.pump()
            if updated_rect:
                pygame.display.update(updated_rect)

        self._show_overlay(get_translated_text('smile'), alpha)
        self._window.show_image(self._get_preview_image())

    def stop_preview(self):
        """Stop the preview.
        """
        self._hide_overlay()
        self._cam.stopCamera()
        self._window = None

    def capture(self, effect=None):
        """Capture a new picture.
        """
        effect = str(effect).lower()
        if effect not in self.IMAGE_EFFECTS:
            raise ValueError("Invalid capture effect '{}' (choose among {})".format(effect, self.IMAGE_EFFECTS))

        self._cam.initCamera(self.resolution[0], self.resolution[1],
                             libcamera.PixelFormat.RGB888, buffercount=4,
                             rotation=self.capture_rotation)
        if self.capture_iso != self.preview_iso:
            self._cam.set(libcamera.ExposureTime, self.capture_iso)

        LOGGER.debug("Taking capture at resolution %s", self.resolution)
        ret, data = self._cam.readFrame()
        if not ret:
            raise IOError("Can not capture frame")

        if self.capture_iso != self.preview_iso:
            self._cam.set(libcamera.ExposureTime, self.preview_iso)

        self._captures.append((data.imageData, effect))
        self._cam.returnFrameBuffer(data)
        time.sleep(0.5)  # To let time to see "Smile"

        self._hide_overlay()  # If stop_preview() has not been called

    def quit(self):
        """Close the camera driver, it's definitive.
        """
        if self._cam:
            self._cam.closeCamera()

```

**Comment by anxuae** [comment]
First of all, you have 2 class LibcameraCamera in the plugin, so please remove one.

Then, it seems that takin a picture has failed... but I can not help because I can not test

**Comment by tityann** [comment]
so with your driver/plugin edited on 11/10/2021
and includ the ```self._cam.startCamera()```

```javascript
import time
import pibooth
import libcamera

from pibooth.utils import LOGGER
from pibooth.camera.base import BaseCamera


__version__ = "1.0.0"


class LibcameraCamera(BaseCamera):

    """Libcamera camera management.
    """

    IMAGE_EFFECTS = [u'none',
                     u'blur',
                     u'contour',
                     u'detail',
                     u'edge_enhance',
                     u'edge_enhance_more',
                     u'emboss',
                     u'find_edges',
                     u'smooth',
                     u'smooth_more',
                     u'sharpen']

    def __init__(self, camera_proxy):
        super(LibcameraCamera, self).__init__(camera_proxy)
        self._overlay_alpha = 255

    def _specific_initialization(self):
        """Camera initialization.
        """
        self._cam.initCamera(self.resolution[0], self.resolution[1],
                             libcamera.PixelFormat.RGB888, buffercount=4,
                             rotation=self.preview_rotation)
        self._cam.set(libcamera.ExposureTime, self.preview_iso)
        framerate = 30
        frame_time = 1000000 // framerate
        self._cam.set(libcamera.FrameDurationLimits, [frame_time, frame_time])

    def _show_overlay(self, text, alpha):
        """Add an image as an overlay.
        """
        if self._window:  # No window means no preview displayed
            rect = self.get_rect()
            self._overlay_alpha = alpha
            self._overlay = self.build_overlay((rect.width, rect.height), str(te                                                                                                                                                             xt), alpha)

    def _get_preview_image(self):
        """Capture a new preview image.
        """
        rect = self.get_rect()

        ret, data = self._cam.readFrame()
        if not ret:
            raise IOError("Can not get camera preview image")

        image = Image.open(io.BytesIO(data.imageData))
        self._cam.returnFrameBuffer(data)
        # Crop to keep aspect ratio of the resolution
        image = image.crop(sizing.new_size_by_croping_ratio(image.size, self.res                                                                                                                                                             olution))
        # Resize to fit the available space in the window
        image = image.resize(sizing.new_size_keep_aspect_ratio(image.size, (rect                                                                                                                                                             .width, rect.height), 'outer'))

        if self.preview_flip:
            image = image.transpose(Image.FLIP_LEFT_RIGHT)

        if self._overlay:
            image.paste(self._overlay, (0, 0), self._overlay)
        return image

    def _post_process_capture(self, capture_data):
        """Rework capture data.

        :param capture_data: couple (frame, effect)
        :type capture_data: tuple
        """
        frame, effect = capture_data
        image = Image.open(io.BytesIO(frame))

        # Crop to keep aspect ratio of the resolution
        image = image.crop(sizing.new_size_by_croping_ratio(image.size, self.res                                                                                                                                                             olution))
        # Resize to fit the resolution
        image = image.resize(sizing.new_size_keep_aspect_ratio(image.size, self.                                                                                                                                                             resolution, 'outer'))

        if self.capture_flip:
            image = image.transpose(Image.FLIP_LEFT_RIGHT)

        if effect != 'none':
            image = image.filter(getattr(ImageFilter, effect.upper()))

        return image

    def preview(self, window, flip=True):
        """Setup the preview.
        """
        self._window = window
        self.preview_flip = flip
        self._cam.startCamera()
        self._window.show_image(self._get_preview_image())

    def preview_countdown(self, timeout, alpha=80):
        """Show a countdown of `timeout` seconds on the preview.
        Returns when the countdown is finished.
        """
        timeout = int(timeout)
        if timeout < 1:
            raise ValueError("Start time shall be greater than 0")

        timer = PoolingTimer(timeout)
        while not timer.is_timeout():
            remaining = int(timer.remaining() + 1)
            if self._overlay is None or remaining != timeout:
                # Rebluid overlay only if remaining number has changed
                self._show_overlay(str(remaining), alpha)
                timeout = remaining

            updated_rect = self._window.show_image(self._get_preview_image())
            pygame.event.pump()
            if updated_rect:
                pygame.display.update(updated_rect)

        self._show_overlay(get_translated_text('smile'), alpha)
        self._window.show_image(self._get_preview_image())

    def preview_wait(self, timeout, alpha=80):
        """Wait the given time.
        """
        timeout = int(timeout)
        if timeout < 1:
            raise ValueError("Start time shall be greater than 0")

        timer = PoolingTimer(timeout)
        while not timer.is_timeout():
            updated_rect = self._window.show_image(self._get_preview_image())
            pygame.event.pump()
            if updated_rect:
                pygame.display.update(updated_rect)

        self._show_overlay(get_translated_text('smile'), alpha)
        self._window.show_image(self._get_preview_image())

    def stop_preview(self):
        """Stop the preview.
        """
        self._hide_overlay()
        self._cam.stopCamera()
        self._window = None

    def capture(self, effect=None):
        """Capture a new picture.
        """
        effect = str(effect).lower()
        if effect not in self.IMAGE_EFFECTS:
            raise ValueError("Invalid capture effect '{}' (choose among {})".for                                                                                                                                                             mat(effect, self.IMAGE_EFFECTS))

        if self.capture_iso != self.preview_iso:
            self._cam.set(libcamera.ExposureTime, self.capture_iso)

        LOGGER.debug("Taking capture at resolution %s", self.resolution)
        ret, data = self._cam.readFrame()
        if not ret:
            raise IOError("Can not capture frame")

        if self.capture_iso != self.preview_iso:
            self._cam.set(libcamera.ExposureTime, self.preview_iso)

        self._captures.append((data.imageData, effect))
        self._cam.returnFrameBuffer(data)
        time.sleep(0.5)  # To let time to see "Smile"

        self._hide_overlay()  # If stop_preview() has not been called

    def quit(self):
        """Close the camera driver, it's definitive.
        """
        if self._cam:
            self._cam.closeCamera()


@pibooth.hookimpl
def pibooth_setup_camera(cfg):
    libcam_cam_proxy = libcamera.libcamera()

    LOGGER.info("Configuring hybrid camera (libcamera) ...")
    return LibcameraCamera(libcam_cam_proxy)
```

and the log is
```
pi@raspberrypi:/tmp $ cat pibooth.log
[ DEBUG   ] pibooth           : Plugin found at '/home/pi/pibooth_driver_arducam.py'
[ INFO    ] pibooth           : Installed plugins: driver_arducam-1.0.0
[ INFO    ] pibooth           : Starting the photo booth application on Raspberry pi 4B
[ INFO    ] pibooth           : Configuring hybrid camera (libcamera) ...
[ WARNING ] pibooth           : No printer found (pycups or pycups-notify not installed)
[ DEBUG   ] pibooth           : Activate state 'wait'
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'IHDR' 16 13
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'bKGD' 41 6
[ DEBUG   ] PIL.PngImagePlugin: b'bKGD' 41 6 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'pHYs' 59 9
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'tIME' 80 7
[ DEBUG   ] PIL.PngImagePlugin: b'tIME' 80 7 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'iTXt' 99 29
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'IDAT' 140 5756
[ DEBUG   ] pibooth           : Activate state 'choose'
[ INFO    ] pibooth           : Show picture choice (nothing selected)
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'IHDR' 16 13
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'iCCP' 41 388
[ DEBUG   ] PIL.PngImagePlugin: iCCP profile name b'ICC profile'
[ DEBUG   ] PIL.PngImagePlugin: Compression method 0
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'bKGD' 441 6
[ DEBUG   ] PIL.PngImagePlugin: b'bKGD' 441 6 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'pHYs' 459 9
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'tIME' 480 7
[ DEBUG   ] PIL.PngImagePlugin: b'tIME' 480 7 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'tEXt' 499 25
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'IDAT' 536 8192
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'IHDR' 16 13
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'iCCP' 41 388
[ DEBUG   ] PIL.PngImagePlugin: iCCP profile name b'ICC profile'
[ DEBUG   ] PIL.PngImagePlugin: Compression method 0
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'bKGD' 441 6
[ DEBUG   ] PIL.PngImagePlugin: b'bKGD' 441 6 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'pHYs' 459 9
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'tIME' 480 7
[ DEBUG   ] PIL.PngImagePlugin: b'tIME' 480 7 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'tEXt' 499 25
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'IDAT' 536 8192
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'IHDR' 16 13
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'bKGD' 41 6
[ DEBUG   ] PIL.PngImagePlugin: b'bKGD' 41 6 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'pHYs' 59 9
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'tIME' 80 7
[ DEBUG   ] PIL.PngImagePlugin: b'tIME' 80 7 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'iTXt' 99 29
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'IDAT' 140 5756
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'IHDR' 16 13
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'bKGD' 41 6
[ DEBUG   ] PIL.PngImagePlugin: b'bKGD' 41 6 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'pHYs' 59 9
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'tIME' 80 7
[ DEBUG   ] PIL.PngImagePlugin: b'tIME' 80 7 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'iTXt' 99 29
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'IDAT' 140 5756
[ DEBUG   ] pibooth           : took 0.194 seconds
[ DEBUG   ] pibooth           : Activate state 'chosen'
[ INFO    ] pibooth           : Show picture choice (1 captures selected)
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'IHDR' 16 13
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'iCCP' 41 388
[ DEBUG   ] PIL.PngImagePlugin: iCCP profile name b'ICC profile'
[ DEBUG   ] PIL.PngImagePlugin: Compression method 0
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'bKGD' 441 6
[ DEBUG   ] PIL.PngImagePlugin: b'bKGD' 441 6 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'pHYs' 459 9
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'tIME' 480 7
[ DEBUG   ] PIL.PngImagePlugin: b'tIME' 480 7 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'tEXt' 499 25
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'IDAT' 536 8192
[ DEBUG   ] pibooth           : took 0.110 seconds
[ DEBUG   ] pibooth           : Activate state 'preview'
[ INFO    ] pibooth           : Show preview before next capture
[ ERROR   ] pibooth           : Can not get camera preview image
[ DEBUG   ] pibooth           : Back to failsafe state due to error:
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/pibooth/states.py", line 91, in set_state
    hook(cfg=self.cfg, app=self.app, win=self.win)
  File "/usr/local/lib/python3.7/dist-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/usr/local/lib/python3.7/dist-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/local/lib/python3.7/dist-packages/pluggy/_manager.py", line 327, in traced_hookexec
    return outcome.get_result()
  File "/usr/local/lib/python3.7/dist-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.7/dist-packages/pluggy/_result.py", line 33, in from_call
    result = func()
  File "/usr/local/lib/python3.7/dist-packages/pluggy/_manager.py", line 324, in <lambda>
    lambda: oldcall(hook_name, hook_impls, kwargs, firstresult)
  File "/usr/local/lib/python3.7/dist-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python3.7/dist-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.7/dist-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/home/pi/.local/lib/python3.7/site-packages/pibooth/plugins/camera_plugin.py", line 69, in state_preview_enter
    app.camera.preview(win)
  File "/home/pi/pibooth_driver_arducam.py", line 105, in preview
    self._window.show_image(self._get_preview_image())
  File "/home/pi/pibooth_driver_arducam.py", line 61, in _get_preview_image
    raise IOError("Can not get camera preview image")
OSError: Can not get camera preview image
[ DEBUG   ] pibooth           : Activate state 'failsafe'
[ ERROR   ] pibooth           : system='Linux', node='raspberrypi', release='5.10.63-v7l+', version='#1457 SMP Tue Sep 28 11:26:14 BST 2021', machine='armv7l', processor=''
 ***********************************************************************************
 *                     Oops! It seems that pibooth has crached                     *
 *     You can report an issue on https://github.com/pibooth/pibooth/issues/new    *
 *                       and post the file: /tmp/pibooth.log                       *
 ***********************************************************************************
[ DEBUG   ] pibooth           : Activate state 'wait'
````

**Comment by tityann** [comment]
i tried to put the 
```self._cam.startCamera()```
in the section ```def _specific_initialization(self):```
and now i pass thz reponse `````raise IOError("Can not get camera preview image")````
now i have
```
File "/home/pi/pibooth_driver_arducam.py", line 64, in _get_preview_image
    image = Image.open(io.BytesIO(data.imageData))
NameError: name 'Image' is not defined
````
maybe a mistake in defining ""image" ???

**Comment by anxuae** [comment]
Can you ask to libcamera team how to load image with PIL lib?

**Comment by anxuae** [comment]
Hi @tityann , can you try to replace `Image.open(io.BytesIO(data.imageData))`  with `Image.fromarray(data.imageData)` ?

**Comment by tityann** [comment]
hello @anxuae 
now the new issue is
`````
 File "/home/pi/pibooth_driver_arducam.py", line 67, in _get_preview_image
    image = image.crop(sizing.new_size_by_croping_ratio(image.size, self.resolution))
NameError: name 'sizing' is not defined
```

I don't manage to identify which library i have to import

**Comment by tityann** [comment]
for "size" it seem to depend from
```import numpy as np```
but still the same error....
i don't manage to find information for "sizing"

**Comment by tityann** [comment]
now i have
````
 image = Image.open(io.BytesIO(frame))
  File "/usr/local/lib/python3.7/dist-packages/PIL/Image.py", line 3024, in open
    "cannot identify image file %r" % (filename if filename else fp)
````

**Comment by tityann** [comment]
i don't know if the camera is well intitialized
becaus if i ask to take another photo it crash with
````
  self._window.show_image(self._get_preview_image())
  File "/home/pi/pibooth_driver_arducam.py", line 69, in _get_preview_image
    raise IOError("Can not get camera preview image")
````
when i told you that i have move the init of the camera earlier in the script, do i did it well ?
i put it ther
```javascript
   def __init__(self, camera_proxy):
        super(LibcameraCamera, self).__init__(camera_proxy)
        self._overlay_alpha = 255

    def _specific_initialization(self):
        """Camera initialization.
        """
        self._cam.initCamera(self.resolution[0], self.resolution[1],
                             libcamera.PixelFormat.RGB888, buffercount=4,
                             rotation=self.preview_rotation)
        self._cam.set(libcamera.ExposureTime, self.preview_iso)
        framerate = 30
        frame_time = 1000000 // framerate
        self._cam.set(libcamera.FrameDurationLimits, [frame_time, frame_time])
        self._cam.startCamera()
```

**Comment by anxuae** [comment]
No, it shall be put in the `preview` function.

**Comment by anxuae** [comment]
def preview(self, window, flip=True):
        """Setup the preview.
        """
        self._window = window
        self.preview_flip = flip
        self._cam.startCamera()
        self._window.show_image(self._get_preview_image())

**Comment by anxuae** [comment]
Can you post your current plugin?

**Comment by tityann** [comment]
ok i will try this evening.
you commented the "ExposureTime setting", but this option is only on the capture ? , the preview have no "ExposureTime setting" but the preview is also black

**Comment by anxuae** [comment]
Can you save the frame in a file and attache it? I will try to load it.

I've modified the plugin to write frames in a file `frame.txt`

**Comment by anxuae** [comment]
ok, modified again, the file is now called `frame.jpg`. it should work

**Comment by anxuae** [comment]
Bullseye, the new version of Raspberry Pi OS, introduce libcamera and break compatibility with pibooth (see https://www.raspberrypi.com/news/raspberry-pi-os-debian-bullseye/).

It's urgent to finalize the libcamera driver for pibooth

**Comment by tityann** [comment]
hello, i had not enough time to see more on my test machine
now bullseyes only use libcamera, , is there someone else who have tried ?
what must i do to help

in the last test, the video of preview was very slow

**Comment by Flo4Git** [comment]
> hello, i had not enough time to see more on my test machine
> 
> now bullseyes only use libcamera, , is there someone else who have tried ?
> 
> what must i do to help
> 
> 
> 
> in the last test, the video of preview was very slow

Hello,
I have tried, and confirmed not compatible. 
You have to install back previous version Buster. 
Regards

**Comment by anxuae** [comment]
Will be solved with picamera2, waiting for official release

https://github.com/raspberrypi/picamera2

**Comment by klemva** [comment]
Hi guys, am i understand Richter, that Arducam will work after picamera2 will release oficial package?

I buy one today for testing.

thank you for answer:)

**Comment by anxuae** [comment]
Hi @klemva , yes it should be compatible

**Comment by apicole** [comment]
> Will be solved with picamera2, waiting for official release
> 
> https://github.com/raspberrypi/picamera2

I m waiting for that since I upgraded my pi to Bullseye.. :-)

**Comment by yaazzz** [comment]
Hello, do we have any update on picamera2 or any tester needed?

**Comment by dpdamian** [comment]
interested in the in the timeline of the fix also, would prefer not to have to return the camera.

**Comment by lxne** [comment]
Hi, I have a new Pi High Quality Camera working with bullseye and libcamera. Should it work with pibooth if I would install picamera2 0.3.7 Beta Release 6?

**Comment by MikkeBoomBoom** [comment]
Hi, I’m struggling with a V3 picam as well, promised my sister in law a new system in two weeks *sigh* do you have an ETA? 😅

**Comment by LoKa67** [comment]
Hi, 
I'm really interested in the release you're working on, any update regarding the release date?
Thanks

**Comment by loranger** [comment]
Hello, 
I would be really happy to use my brand new pi camera v3 (and its autofocus) on my pi booth too.
Do we have any ETA ?

Thanks 👍🏻

**Comment by MartinN3** [comment]
Until it's done i recommend to inform about this in README.

**Comment by Hylobat** [comment]
The picam V3's auto focus  is the only thing missing to Pibooth to make it the ultimate photobooth solution. Hope it will come soon. 🤞

**Comment by werdeil** [comment]
Closed: picamera2 (libcamera) support is available since pibooth 2.1.0 on Raspberry Pi OS Bookworm, see the installation page. The 3.x branch will use the same driver (see the pinned issue).
