### ISSUE TITLE
{date} in footer text throws execption

### ISSUE THREAD

**Issue by mhilcher** [pibooth/pibooth#352]
I used the example from the docs 

```
# Secondary text displayed
footer_text2 = A custom date is {date.year}-{date.month}-{date.day}
```
I tried it without quotes and with quotes.

It always gives me the exception when I do pibooth-regen:

```
Traceback (most recent call last):
  File "/usr/local/bin/pibooth-regen", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/pibooth/scripts/regenerate.py", line 81, in main
    regenerate_all_images(plugin_manager, config, path)
  File "/usr/local/lib/python3.9/dist-packages/pibooth/scripts/regenerate.py", line 55, in regenerate_all_images
    factory = plugin_manager.hook.pibooth_setup_picture_factory(cfg=config,
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_manager.py", line 327, in traced_hookexec
    return outcome.get_result()
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_result.py", line 33, in from_call
    result = func()
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_manager.py", line 324, in <lambda>
    lambda: oldcall(hook_name, hook_impls, kwargs, firstresult)
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "/usr/local/lib/python3.9/dist-packages/pibooth/plugins/picture_plugin.py", line 49, in pibooth_setup_picture_factory
    cfg.get('PICTURE', 'footer_text2').strip('"').format(**self.texts_vars)]
KeyError: 'date'
```
What am I doing wrong?
Thx

**Comment by anxuae** [comment]
Pushed a fix on master branch. Will be available in next release
