### ISSUE TITLE
pibooth will only take 1 picture it will not take 4 pictures, it crashes after one photo

### ISSUE THREAD

**Issue by MrNm** [pibooth/pibooth#485]
pibooth will only take 1 picture it will not take 4 pictures, it crashes after one photo. I am using a Nikon D3400 with Gphoto2 & CUPs.

I do have auto focus set on the DSLR and in the configs of pibooth I have only changed the font and the footer.

** Logs **
[ INFO    ] pibooth           : Installed plugins: 
[ INFO    ] pibooth           : Starting the photo booth application on Raspberry pi 3B
[ DEBUG   ] pibooth           : Fallback to pibooth default camera management system
[ DEBUG   ] pibooth           : Found gPhoto2 cameras on ports: 'usb:001,006'
[ INFO    ] pibooth           : Configuring gPhoto2 camera ...
[ DEBUG   ] pibooth.gphoto2   : _get_config [config.c:10350]: Type of property 'Lens Name' expected: 0x0002 got: 0x0004
[ DEBUG   ] pibooth.gphoto2   : _get_config [config.c:10366]: Widget get of property 'Lens Name' failed, trying to see if we have another...
[ DEBUG   ] pibooth.gphoto2   : _get_config [config.c:10350]: Type of property 'Available Shots' expected: 0x0006 got: 0x0004
[ DEBUG   ] pibooth.gphoto2   : _get_config [config.c:10350]: Type of property 'Live View AF Mode' expected: 0x0001 got: 0x0002
[ DEBUG   ] pibooth.gphoto2   : _get_config [config.c:10366]: Widget get of property 'Live View AF Mode' failed, trying to see if we have another...
[ DEBUG   ] pibooth           : Getting option actions/viewfinder=0
[ DEBUG   ] pibooth           : Setting option imgsettings/iso=100
[ DEBUG   ] pibooth.gphoto2   : _get_config [config.c:10350]: Type of property 'Lens Name' expected: 0x0002 got: 0x0004
[ DEBUG   ] pibooth.gphoto2   : _get_config [config.c:10366]: Widget get of property 'Lens Name' failed, trying to see if we have another...
[ DEBUG   ] pibooth.gphoto2   : _get_config [config.c:10350]: Type of property 'Available Shots' expected: 0x0006 got: 0x0004
[ DEBUG   ] pibooth.gphoto2   : _get_config [config.c:10350]: Type of property 'Live View AF Mode' expected: 0x0001 got: 0x0002
[ DEBUG   ] pibooth.gphoto2   : _get_config [config.c:10366]: Widget get of property 'Live View AF Mode' failed, trying to see if we have another...
[ DEBUG   ] pibooth           : Setting option settings/capturetarget=Memory card
[ DEBUG   ] pibooth.gphoto2   : _get_config [config.c:10350]: Type of property 'Lens Name' expected: 0x0002 got: 0x0004
[ DEBUG   ] pibooth.gphoto2   : _get_config [config.c:10366]: Widget get of property 'Lens Name' failed, trying to see if we have another...
[ DEBUG   ] pibooth.gphoto2   : _get_config [config.c:10350]: Type of property 'Available Shots' expected: 0x0006 got: 0x0004
[ DEBUG   ] pibooth.gphoto2   : _get_config [config.c:10350]: Type of property 'Live View AF Mode' expected: 0x0001 got: 0x0002
[ DEBUG   ] pibooth.gphoto2   : _get_config [config.c:10366]: Widget get of property 'Live View AF Mode' failed, trying to see if we have another...
[ INFO    ] pibooth           : Connected to printer 'Canon_SELPHY'
[ DEBUG   ] pibooth           : Activate state 'wait'
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'IHDR' 16 13
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'bKGD' 41 6
[ DEBUG   ] PIL.PngImagePlugin: b'bKGD' 41 6 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'pHYs' 59 9
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'tIME' 80 7
[ DEBUG   ] PIL.PngImagePlugin: b'tIME' 80 7 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'iTXt' 99 29
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'IDAT' 140 5756
[ DEBUG   ] pibooth           : took 1.107 seconds
[ DEBUG   ] pibooth           : Activate state 'choose'
[ INFO    ] pibooth           : Show picture choice (nothing selected)
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'IHDR' 16 13
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'iCCP' 41 388
[ DEBUG   ] PIL.PngImagePlugin: iCCP profile name b'ICC profile'
[ DEBUG   ] PIL.PngImagePlugin: Compression method 0
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'bKGD' 441 6
[ DEBUG   ] PIL.PngImagePlugin: b'bKGD' 441 6 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'pHYs' 459 9
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'tIME' 480 7
[ DEBUG   ] PIL.PngImagePlugin: b'tIME' 480 7 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'tEXt' 499 25
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'IDAT' 536 8192
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'IHDR' 16 13
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'iCCP' 41 388
[ DEBUG   ] PIL.PngImagePlugin: iCCP profile name b'ICC profile'
[ DEBUG   ] PIL.PngImagePlugin: Compression method 0
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'bKGD' 441 6
[ DEBUG   ] PIL.PngImagePlugin: b'bKGD' 441 6 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'pHYs' 459 9
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'tIME' 480 7
[ DEBUG   ] PIL.PngImagePlugin: b'tIME' 480 7 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'tEXt' 499 25
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'IDAT' 536 8192
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'IHDR' 16 13
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'bKGD' 41 6
[ DEBUG   ] PIL.PngImagePlugin: b'bKGD' 41 6 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'pHYs' 59 9
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'tIME' 80 7
[ DEBUG   ] PIL.PngImagePlugin: b'tIME' 80 7 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'iTXt' 99 29
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'IDAT' 140 5756
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'IHDR' 16 13
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'bKGD' 41 6
[ DEBUG   ] PIL.PngImagePlugin: b'bKGD' 41 6 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'pHYs' 59 9
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'tIME' 80 7
[ DEBUG   ] PIL.PngImagePlugin: b'tIME' 80 7 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'iTXt' 99 29
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'IDAT' 140 5756
[ DEBUG   ] pibooth           : took 1.853 seconds
[ DEBUG   ] pibooth           : Activate state 'chosen'
[ INFO    ] pibooth           : Show picture choice (4 captures selected)
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'IHDR' 16 13
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'iCCP' 41 388
[ DEBUG   ] PIL.PngImagePlugin: iCCP profile name b'ICC profile'
[ DEBUG   ] PIL.PngImagePlugin: Compression method 0
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'bKGD' 441 6
[ DEBUG   ] PIL.PngImagePlugin: b'bKGD' 441 6 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'pHYs' 459 9
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'tIME' 480 7
[ DEBUG   ] PIL.PngImagePlugin: b'tIME' 480 7 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'tEXt' 499 25
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'IDAT' 536 8192
[ DEBUG   ] pibooth           : took 4.210 seconds
[ DEBUG   ] pibooth           : Activate state 'preview'
[ INFO    ] pibooth           : Show preview before next capture
[ DEBUG   ] pibooth           : Setting option actions/viewfinder=1
[ DEBUG   ] pibooth.gphoto2   : _get_config [config.c:10350]: Type of property 'Lens Name' expected: 0x0002 got: 0x0004
[ DEBUG   ] pibooth.gphoto2   : _get_config [config.c:10366]: Widget get of property 'Lens Name' failed, trying to see if we have another...
[ DEBUG   ] pibooth.gphoto2   : _get_config [config.c:10350]: Type of property 'Available Shots' expected: 0x0006 got: 0x0004
[ DEBUG   ] pibooth.gphoto2   : _get_config [config.c:10350]: Type of property 'Live View AF Mode' expected: 0x0001 got: 0x0002
[ DEBUG   ] pibooth.gphoto2   : _get_config [config.c:10366]: Widget get of property 'Live View AF Mode' failed, trying to see if we have another...
[ DEBUG   ] pibooth.gphoto2   : ptp_usb_getresp [usb.c:515]: PTP_OC 0x90c8 receiving resp failed: PTP Device Busy (0x2019)
[ DEBUG   ] pibooth.gphoto2   : ptp_usb_getresp [usb.c:515]: PTP_OC 0x90c8 receiving resp failed: PTP Device Busy (0x2019)
[ DEBUG   ] pibooth.gphoto2   : ptp_usb_getresp [usb.c:515]: PTP_OC 0x90c8 receiving resp failed: PTP Device Busy (0x2019)
[ DEBUG   ] pibooth.gphoto2   : ptp_usb_getresp [usb.c:515]: PTP_OC 0x90c8 receiving resp failed: PTP Device Busy (0x2019)
[ DEBUG   ] pibooth.gphoto2   : ptp_usb_getresp [usb.c:515]: PTP_OC 0x90c8 receiving resp failed: PTP Device Busy (0x2019)
[ DEBUG   ] pibooth.gphoto2   : ptp_usb_getresp [usb.c:515]: PTP_OC 0x90c8 receiving resp failed: PTP Device Busy (0x2019)
[ DEBUG   ] pibooth.gphoto2   : ptp_usb_getresp [usb.c:515]: PTP_OC 0x90c8 receiving resp failed: PTP Device Busy (0x2019)
[ DEBUG   ] pibooth.gphoto2   : ptp_usb_getresp [usb.c:515]: PTP_OC 0x90c8 receiving resp failed: PTP Device Busy (0x2019)
[ DEBUG   ] pibooth.gphoto2   : ptp_usb_getresp [usb.c:515]: PTP_OC 0x90c8 receiving resp failed: PTP Device Busy (0x2019)
[ DEBUG   ] pibooth.gphoto2   : ptp_usb_getresp [usb.c:515]: PTP_OC 0x90c8 receiving resp failed: PTP Device Busy (0x2019)
[ DEBUG   ] pibooth.gphoto2   : ptp_usb_getresp [usb.c:515]: PTP_OC 0x90c2 receiving resp failed: Change Camera Mode Failed (0xa003)
[ DEBUG   ] pibooth           : Add to buffer the image '1353359144'
[ DEBUG   ] pibooth           : No translation defined for 'en/capture' key
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'IHDR' 16 13
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'iCCP' 41 388
[ DEBUG   ] PIL.PngImagePlugin: iCCP profile name b'ICC profile'
[ DEBUG   ] PIL.PngImagePlugin: Compression method 0
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'bKGD' 441 6
[ DEBUG   ] PIL.PngImagePlugin: b'bKGD' 441 6 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'pHYs' 459 9
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'tIME' 480 7
[ DEBUG   ] PIL.PngImagePlugin: b'tIME' 480 7 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'tEXt' 499 25
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'IDAT' 536 8192
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'IHDR' 16 13
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'iCCP' 41 388
[ DEBUG   ] PIL.PngImagePlugin: iCCP profile name b'ICC profile'
[ DEBUG   ] PIL.PngImagePlugin: Compression method 0
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'bKGD' 441 6
[ DEBUG   ] PIL.PngImagePlugin: b'bKGD' 441 6 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'pHYs' 459 9
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'tIME' 480 7
[ DEBUG   ] PIL.PngImagePlugin: b'tIME' 480 7 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'tEXt' 499 25
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'IDAT' 536 5653
[ DEBUG   ] pibooth           : Add to buffer the image '1353249744'
[ DEBUG   ] pibooth           : Add to buffer the image '1353359144'
[ DEBUG   ] pibooth           : Add to buffer the image '1353249744'
[ DEBUG   ] pibooth           : Add to buffer the image '1353359144'
[ DEBUG   ] pibooth           : Add to buffer the image '1353249744'
[ DEBUG   ] pibooth           : Add to buffer the image '1353359144'
[ DEBUG   ] pibooth           : Add to buffer the image '1353249744'
[ DEBUG   ] pibooth           : Add to buffer the image '1353359144'
[ DEBUG   ] pibooth           : Add to buffer the image '1353249744'
[ DEBUG   ] pibooth           : Add to buffer the image '1353359144'
[ DEBUG   ] pibooth           : Add to buffer the image '1353249744'
[ DEBUG   ] pibooth           : Add to buffer the image '1353359144'
[ DEBUG   ] pibooth           : Add to buffer the image '1353249744'
[ DEBUG   ] pibooth           : Add to buffer the image '1353359144'
[ DEBUG   ] pibooth           : Add to buffer the image '1353249744'
[ DEBUG   ] pibooth           : Add to buffer the image '1353359144'
[ DEBUG   ] pibooth           : Add to buffer the image '1353249744'
[ DEBUG   ] pibooth           : Add to buffer the image '1353359144'
[ DEBUG   ] pibooth           : Add to buffer the image '1353249744'
[ DEBUG   ] pibooth           : Add to buffer the image '1353249600'
[ DEBUG   ] pibooth           : Add to buffer the image '1353249744'
[ DEBUG   ] pibooth           : Add to buffer the image '1353249600'
[ DEBUG   ] pibooth           : Add to buffer the image '1353249744'
[ DEBUG   ] pibooth           : Add to buffer the image '1353249600'
[ DEBUG   ] pibooth           : Add to buffer the image '1353249744'
[ DEBUG   ] pibooth           : Add to buffer the image '1353249600'
[ DEBUG   ] pibooth           : Add to buffer the image '1353249744'
[ DEBUG   ] pibooth           : Add to buffer the image '1353249600'
[ DEBUG   ] pibooth           : Add to buffer the image '1353249744'
[ DEBUG   ] pibooth           : Add to buffer the image '1353249600'
[ DEBUG   ] pibooth           : Add to buffer the image '1353249744'
[ DEBUG   ] pibooth           : Add to buffer the image '1353249600'
[ DEBUG   ] pibooth           : Add to buffer the image '1353249744'
[ DEBUG   ] pibooth           : Add to buffer the image '1353249600'
[ DEBUG   ] pibooth           : Add to buffer the image '1353249744'
[ DEBUG   ] pibooth           : Add to buffer the image '1353249600'
[ DEBUG   ] pibooth           : Add to buffer the image '1353357632'
[ DEBUG   ] pibooth           : Add to buffer the image '1353249600'
[ DEBUG   ] pibooth           : Add to buffer the image '1353357632'
[ DEBUG   ] pibooth           : Add to buffer the image '1353249600'
[ DEBUG   ] pibooth           : Add to buffer the image '1353357632'
[ DEBUG   ] pibooth           : Add to buffer the image '1353249600'
[ DEBUG   ] pibooth           : Add to buffer the image '1353357632'
[ DEBUG   ] pibooth           : Add to buffer the image '1353249600'
[ DEBUG   ] pibooth           : Add to buffer the image '1353357632'
[ DEBUG   ] pibooth           : Add to buffer the image '1353249600'
[ DEBUG   ] pibooth           : Add to buffer the image '1353357632'
[ DEBUG   ] pibooth           : Add to buffer the image '1353249600'
[ DEBUG   ] pibooth           : Add to buffer the image '1353357632'
[ DEBUG   ] pibooth           : Add to buffer the image '1353249600'
[ DEBUG   ] pibooth           : Add to buffer the image '1353357632'
[ DEBUG   ] pibooth           : Add to buffer the image '1353249600'
[ DEBUG   ] pibooth           : Add to buffer the image '1353357632'
[ DEBUG   ] pibooth           : Add to buffer the image '1353249600'
[ DEBUG   ] pibooth           : took 4.439 seconds
[ DEBUG   ] pibooth           : Activate state 'capture'
[ INFO    ] pibooth           : Take a capture
[ DEBUG   ] pibooth           : Setting option actions/viewfinder=0
[ DEBUG   ] pibooth.gphoto2   : _get_config [config.c:10350]: Type of property 'Lens Name' expected: 0x0002 got: 0x0004
[ DEBUG   ] pibooth.gphoto2   : _get_config [config.c:10366]: Widget get of property 'Lens Name' failed, trying to see if we have another...
[ DEBUG   ] pibooth.gphoto2   : _get_config [config.c:10350]: Type of property 'Available Shots' expected: 0x0006 got: 0x0004
[ DEBUG   ] pibooth.gphoto2   : _get_config [config.c:10350]: Type of property 'Live View AF Mode' expected: 0x0001 got: 0x0002
[ DEBUG   ] pibooth.gphoto2   : _get_config [config.c:10366]: Widget get of property 'Live View AF Mode' failed, trying to see if we have another...
[ DEBUG   ] pibooth.gphoto2   : ptp_usb_getresp [usb.c:515]: PTP_OC 0x90c8 receiving resp failed: Out of Focus (0xa002)
[ DEBUG   ] pibooth.gphoto2   : camera_nikon_capture [library.c:4023]: 'nikon_wait_busy (params, 100, 1000*1000)' failed: 'Out of Focus' (0xa002)
[ DEBUG   ] pibooth.gphoto2   : gp_context_error: Out of Focus
[ DEBUG   ] pibooth.gphoto2   : gp_camera_capture [gphoto2-camera.c:1339]: 'camera->functions->capture (camera, type, path, context)' failed: -1
[ ERROR   ] pibooth           : [-1] Unspecified error
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pibooth/booth.py", line 402, in main_loop
    self._machine.process(events)
  File "/usr/local/lib/python3.9/dist-packages/pibooth/states.py", line 53, in process
    hook(cfg=self.cfg, app=self.app, win=self.win, events=events)
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_manager.py", line 327, in traced_hookexec
    return outcome.get_result()
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_result.py", line 33, in from_call
    result = func()
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_manager.py", line 324, in <lambda>
    lambda: oldcall(hook_name, hook_impls, kwargs, firstresult)
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.9/dist-packages/pibooth/plugins/camera_plugin.py", line 103, in state_capture_do
    app.camera.capture(effect)
  File "/usr/local/lib/python3.9/dist-packages/pibooth/camera/gphoto.py", line 298, in capture
    self._captures.append((self._cam.capture(gp.GP_CAPTURE_IMAGE), effect))
gphoto2.GPhoto2Error: [-1] Unspecified error
[ ERROR   ] pibooth           : system='Linux', node='raspberrypi', release='6.1.21-v7+', version='#1642 SMP Mon Apr  3 17:20:52 BST 2023', machine='armv7l', processor=''
 ***********************************************************************************
 *                     Oops! It seems that pibooth has crached                     *
 *     You can report an issue on https://github.com/pibooth/pibooth/issues/new    *
 *                       and post the file: /tmp/pibooth.log                       *

**Comment by werdeil** [comment]
Hi @MrNm, as you are using a DSLR that we don't have it is quite difficult to debug more but as you said it seems to be linked to autofocus 
`gp_context_error: Out of Focus`
My best advice would be to go on manual focus to see if it work like that. As Pibooth is simulating live preview by taking multiple shots having to focus for each of them may lead to issue on the camera side.
