### ISSUE TITLE
Error while compiling pygame: IndexError: list out of range

### ISSUE THREAD

**Issue by glxxyxafonso** [pibooth/pibooth#497]
**Describe the bug**
While I was installing pibooth via pip, it's giving me this error with pygame.

**Steps to reproduce the bug**
1. type pip install pibooth
2. wait
3. See error.

**Logs**
`    WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
    Using UNIX configuration...
    
    sh: 1: sdl2-config: not found
    sh: 1: sdl2-config: not found
    sh: 1: sdl2-config: not found
    
    Hunting dependencies...
    
    ---
    For help with compilation see:
        https://www.pygame.org/wiki/CompileDebian
    To contribute to pygame development see:
        https://www.pygame.org/contribute.html
    ---
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-wwDjVa/pygame/setup.py", line 400, in <module>
        buildconfig.config.main(AUTO_CONFIG)
      File "buildconfig/config.py", line 241, in main
        deps = CFG.main(**kwds)
      File "buildconfig/config_unix.py", line 194, in main
        DependencyProg('SDL', 'SDL_CONFIG', 'sdl2-config', '2.0', ['sdl']),
      File "buildconfig/config_unix.py", line 39, in __init__
        self.ver = config[0].strip()
    IndexError: list index out of range`

**Environment**
 - OS: Raspberry Pi OS Legacy (Also known as Raspbian Buster)
 - Camera: CREATIVE Live! Cam 1080p Webcamera
 - Pibooth version: straight out of the pip library
 - Hardware: Raspberry Pi Zero W (yes i know it's not supported, but I have been able to boot it but straight crashing (#493) with the recent version of the Raspberry Pi OS.)

**Comment by anxuae** [comment]
Hello @glxxyxafonso 

Please report to [pygame ](https://github.com/pygame/pygame) repository, this is an issue with the build of the library
