### ISSUE TITLE
raise IOError "can not get camera preview image"

### ISSUE THREAD

**Issue by trsupernothing** [pibooth/pibooth#505]
Hello, I believe this is my first time posting to github.  I was eager to try pibooth for the first time.. however whenever I try to start a session / take a picture, pibooth closes unexpectedly and results in the following error.

[ DEBUG   ] PIL.PngImagePlugin: STREAM b'IDAT' 536 8192
[ DEBUG   ] pibooth           : took 4.120 seconds
[ DEBUG   ] pibooth           : Activate state 'preview'
[ INFO    ] pibooth           : Show preview before next capture
[ ERROR   ] pibooth           : Can not get camera preview image
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pibooth/booth.py", line 402, in main_loop
    self._machine.process(events)
  File "/usr/local/lib/python3.9/dist-packages/pibooth/states.py", line 67, in process
    self.set_state(new_state_name)
  File "/usr/local/lib/python3.9/dist-packages/pibooth/states.py", line 98, in set_state
    hook(cfg=self.cfg, app=self.app, win=self.win)
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_hooks.py", line 433, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_manager.py", line 112, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_manager.py", line 418, in traced_hookexec
    return outcome.get_result()
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_result.py", line 108, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_result.py", line 70, in from_call
    result = func()
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_manager.py", line 415, in <lambda>
    lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_callers.py", line 116, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_callers.py", line 80, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.9/dist-packages/pibooth/plugins/camera_plugin.py", line 71, in state_preview_enter
    app.camera.preview(win)
  File "/usr/local/lib/python3.9/dist-packages/pibooth/camera/opencv.py", line 155, in preview
    self._window.show_image(self._get_preview_image())
  File "/usr/local/lib/python3.9/dist-packages/pibooth/camera/opencv.py", line 101, in _get_preview_image
    raise IOError("Can not get camera preview image")
OSError: Can not get camera preview image
[ ERROR   ] pibooth           : system='Linux', node='raspberrypi', release='6.1.21-v8+', version='#1642 SMP PREEM>

I am using a rasperry pi 4 and a v3 rasperry pi camera.   My apologies if I have no provided enough information and am happy to give further details upon request.

**Comment by anxuae** [comment]
Hello,

`pibooth` not compatible with PiOS Bullseye (downgrade to Buster)

See #290
