### ISSUE TITLE
sony a6300 can't take picture after the first shoot

### ISSUE THREAD

**Issue by kuromatiku** [pibooth/pibooth#511]
**Describe the bug**
after the first capture, it's cannot take any more photo, and need to restart pibooth, and cannot take 4 photo collage, but it's working using `gphoto2 --capture-image` command.

also how do i make the GPIO button works? i already connect the buttons to the GPIO pins and it's still not working

thank you.

<details>
  <summary>**Logs**</summary>
  
```
[ INFO    ] pibooth           : Creating the final picture
[ INFO    ] pibooth           : Use OpenCvPictureFactory to create background
[ INFO    ] pibooth           : Use OpenCvPictureFactory to concatenate images
[ INFO    ] pibooth           : Use OpenCvPictureFactory to assemble final image
[ INFO    ] pibooth           : Use OpenCvPictureFactory to draw texts
[ INFO    ] pibooth           : Save image '/home/manggala/Pictures/pibooth/2023-08-25-21-44-22_pibooth.jpg'
[ DEBUG   ] pibooth           : took 4.148 seconds
[ DEBUG   ] pibooth           : Activate state 'finish'
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'IHDR' 16 13
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'iCCP' 41 388
[ DEBUG   ] PIL.PngImagePlugin: iCCP profile name b'ICC profile'
[ DEBUG   ] PIL.PngImagePlugin: Compression method 0
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'bKGD' 441 6
[ DEBUG   ] PIL.PngImagePlugin: b'bKGD' 441 6 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'pHYs' 459 9
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'tIME' 480 7
[ DEBUG   ] PIL.PngImagePlugin: b'tIME' 480 7 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'tEXt' 499 25
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'IDAT' 536 4879
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'IHDR' 16 13
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'iCCP' 41 388
[ DEBUG   ] PIL.PngImagePlugin: iCCP profile name b'ICC profile'
[ DEBUG   ] PIL.PngImagePlugin: Compression method 0
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'bKGD' 441 6
[ DEBUG   ] PIL.PngImagePlugin: b'bKGD' 441 6 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'pHYs' 459 9
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'tIME' 480 7
[ DEBUG   ] PIL.PngImagePlugin: b'tIME' 480 7 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'tEXt' 499 25
[ DEBUG   ] PIL.PngImagePlugin: STREAM b'IDAT' 536 8192
[ DEBUG   ] pibooth           : took 1.078 seconds
[ DEBUG   ] pibooth           : Activate state 'wait'
[ DEBUG   ] pibooth           : Add to buffer the image '1352945328'
[ DEBUG   ] pibooth           : took 1.880 seconds
[ DEBUG   ] pibooth           : Activate state 'chosen'
[ INFO    ] pibooth           : Show picture choice (1 captures selected)
[ DEBUG   ] pibooth           : took 4.030 seconds
[ DEBUG   ] pibooth           : Activate state 'preview'
[ INFO    ] pibooth           : Show preview before next capture
[ DEBUG   ] pibooth           : Add to buffer the image '1352945040'
[ DEBUG   ] pibooth           : Add to buffer the image '1353078600'
[ DEBUG   ] pibooth           : Add to buffer the image '1352945040'
[ DEBUG   ] pibooth           : Add to buffer the image '1353078528'
[ DEBUG   ] pibooth           : Add to buffer the image '1352945040'
[ DEBUG   ] pibooth           : Add to buffer the image '1353078528'
[ DEBUG   ] pibooth           : Add to buffer the image '1352945040'
[ DEBUG   ] pibooth           : Add to buffer the image '1353077448'
[ DEBUG   ] pibooth           : Add to buffer the image '1353078576'
[ DEBUG   ] pibooth           : Add to buffer the image '1353077448'
[ DEBUG   ] pibooth           : Add to buffer the image '1353078576'
[ DEBUG   ] pibooth           : Add to buffer the image '1353077448'
[ DEBUG   ] pibooth           : Add to buffer the image '1352945400'
[ DEBUG   ] pibooth           : Add to buffer the image '1353077448'
[ DEBUG   ] pibooth           : Add to buffer the image '1352945400'
[ DEBUG   ] pibooth           : Add to buffer the image '1353077448'
[ DEBUG   ] pibooth           : Add to buffer the image '1352945400'
[ DEBUG   ] pibooth           : Add to buffer the image '1353077448'
[ DEBUG   ] pibooth           : Add to buffer the image '1352945400'
[ DEBUG   ] pibooth           : Add to buffer the image '1353077448'
[ DEBUG   ] pibooth           : Add to buffer the image '1352945400'
[ DEBUG   ] pibooth           : Add to buffer the image '1353078480'
[ DEBUG   ] pibooth           : Add to buffer the image '1353078576'
[ DEBUG   ] pibooth           : Add to buffer the image '1353078480'
[ DEBUG   ] pibooth           : Add to buffer the image '1353078576'
[ DEBUG   ] pibooth           : Add to buffer the image '1353078480'
[ DEBUG   ] pibooth           : Add to buffer the image '1353078576'
[ DEBUG   ] pibooth           : Add to buffer the image '1353078480'
[ DEBUG   ] pibooth           : Add to buffer the image '1353078576'
[ DEBUG   ] pibooth           : Add to buffer the image '1353078480'
[ DEBUG   ] pibooth           : Add to buffer the image '1353078576'
[ DEBUG   ] pibooth           : Add to buffer the image '1352945016'
[ DEBUG   ] pibooth           : took 3.410 seconds
[ DEBUG   ] pibooth           : Activate state 'capture'
[ INFO    ] pibooth           : Take a capture
[ DEBUG   ] pibooth.gphoto2   : gp_libusb1_read [libusb1.c:614]: 'libusb_bulk_transfer (port->pl->dh, port->settings.usb.inep, (unsigned char*)bytes, size, &curread, port->timeout)' failed: Input/Output error (-1)
[ DEBUG   ] pibooth.gphoto2   : gp_port_read [gphoto2-port.c:440]: Reading 1024 = 0x400 bytes from port failed: Error reading from the port (-34)
[ DEBUG   ] pibooth.gphoto2   : gp_libusb1_clear_halt_lib [libusb1.c:588]: 'libusb_clear_halt(port->pl->dh, internal_ep)' failed: Other error (-99)
[ DEBUG   ] pibooth.gphoto2   : gp_libusb1_read [libusb1.c:614]: 'libusb_bulk_transfer (port->pl->dh, port->settings.usb.inep, (unsigned char*)bytes, size, &curread, port->timeout)' failed: Input/Output error (-1)
[ DEBUG   ] pibooth.gphoto2   : gp_port_read [gphoto2-port.c:440]: Reading 1024 = 0x400 bytes from port failed: Error reading from the port (-34)
[ DEBUG   ] pibooth.gphoto2   : gp_libusb1_clear_halt_lib [libusb1.c:588]: 'libusb_clear_halt(port->pl->dh, internal_ep)' failed: Other error (-99)
[ DEBUG   ] pibooth.gphoto2   : ptp_usb_getdata [usb.c:480]: PTP_OC 0x1008 receiving data failed: PTP General Error (0x2002)
[ DEBUG   ] pibooth.gphoto2   : camera_sony_capture [library.c:4812]: 'ptp_getobjectinfo (params, newobject, &oi)' failed: PTP I/O Error (0x02ff)
[ DEBUG   ] pibooth.gphoto2   : gp_camera_capture [gphoto2-camera.c:1339]: 'camera->functions->capture (camera, type, path, context)' failed: -7
[ ERROR   ] pibooth           : [-7] I/O problem
[ DEBUG   ] pibooth           : Back to failsafe state due to error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pibooth/states.py", line 53, in process
    hook(cfg=self.cfg, app=self.app, win=self.win, events=events)
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_hooks.py", line 433, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_manager.py", line 112, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_manager.py", line 418, in traced_hookexec
    return outcome.get_result()
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_result.py", line 108, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_result.py", line 70, in from_call
    result = func()
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_manager.py", line 415, in <lambda>
    lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_callers.py", line 116, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_callers.py", line 80, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.9/dist-packages/pibooth/plugins/camera_plugin.py", line 103, in state_capture_do
    app.camera.capture(effect)
  File "/usr/local/lib/python3.9/dist-packages/pibooth/camera/gphoto.py", line 298, in capture
    self._captures.append((self._cam.capture(gp.GP_CAPTURE_IMAGE), effect))
gphoto2.GPhoto2Error: [-7] I/O problem
[ DEBUG   ] pibooth           : took 0.747 seconds
[ DEBUG   ] pibooth           : Activate state 'failsafe'
[ ERROR   ] pibooth           : system='Linux', node='manggalastudio', release='6.1.21-v7+', version='#1642 SMP Mon Apr  3 17:20:52 BST 2023', machine='armv7l', processor=''
 ***********************************************************************************
 *                     Oops! It seems that pibooth has crached                     *
 *     You can report an issue on https://github.com/pibooth/pibooth/issues/new    *
 *                       and post the file: /tmp/pibooth.log                       *
 ***********************************************************************************
[ DEBUG   ] pibooth           : took 2.040 seconds
[ DEBUG   ] pibooth           : Activate state 'wait'

```
  
</details>

**Environment**
 - Raspberry Pi OS 32 Bit (bullseye)
 - Sony A6300
 - Pibooth v2.0.8

**Comment by werdeil** [comment]
Hi @kuromatiku, sorry for the late answer:
- The issue on the 4 pictures is often linked to the fact that there is not a SD card on the DSLR, was it the case?
- About the GPIO, it shall be straightforward, did you manage to make it work?
