### ISSUE TITLE
PiBooth crashes after 1st picture

### ISSUE THREAD

**Issue by the3rdpedal** [pibooth/pibooth#516]
**Describe the bug**
Give a clear and concise description of what the bug is.

**Steps to reproduce the bug**
1. Start pi booth
2. select 1 or 4 photos
3. Take photo
4. ** pibooth immediately crashes **

**Logs**
1. Set the `debug` mode in the config
5. Post your config file
6. Copy-paste all the logs from the console
7. Post the `diagnostic.log` file if you are using a DSLR camera (generated by running the command `pibooth-diag`)

LOGS POSTED BELOW:

```
pi@raspberrypi:~ $ pibooth
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
pygame-menu 4.0.7
[ INFO    ] pibooth           : Installed plugins: 
[ INFO    ] pibooth           : Starting the photo booth application on Raspberry pi 4B
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (961) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1
[ INFO    ] pibooth           : Configuring OpenCV camera ...
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (1214) setProperty OpenCV | GStreamer warning: GStreamer: unhandled property
[ INFO    ] pibooth           : Connected to printer '438_Printer_Scott_s_iMac'
[ INFO    ] pibooth           : Show picture choice (nothing selected)
[ INFO    ] pibooth           : Show picture choice (1 captures selected)
[ INFO    ] pibooth           : Show preview before next capture
[ INFO    ] pibooth           : Take a capture
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (1824) handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module v4l2src0 reported: Internal data stream error.
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (536) startPipeline OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (1085) setProperty OpenCV | GStreamer warning: no pipeline
[ ERROR   ] pibooth           : Can not capture frame
[ ERROR   ] pibooth           : system='Linux', node='raspberrypi', release='6.1.21-v8+', version='#1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023', machine='aarch64', processor=''
 ***********************************************************************************
 *                     Oops! It seems that pibooth has crached                     *
 *     You can report an issue on https://github.com/pibooth/pibooth/issues/new    *
 *                       and post the file: /tmp/pibooth.log                       *
 ***********************************************************************************
^C[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (501) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
Traceback (most recent call last):
  File "/usr/local/bin/pibooth", line 33, in <module>
    sys.exit(load_entry_point('pibooth', 'console_scripts', 'pibooth')())
  File "/home/pi/pibooth/pibooth/booth.py", line 491, in main
    app.main_loop()
  File "/home/pi/pibooth/pibooth/booth.py", line 404, in main_loop
    pygame.display.update()
KeyboardInterrupt
^[[A
pi@raspberrypi:~ $ pibooth
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
pygame-menu 4.0.7
[ INFO    ] pibooth           : Installed plugins: 
[ INFO    ] pibooth           : Starting the photo booth application on Raspberry pi 4B
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (961) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1
[ INFO    ] pibooth           : Configuring OpenCV camera ...
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (1214) setProperty OpenCV | GStreamer warning: GStreamer: unhandled property
[ INFO    ] pibooth           : Connected to printer '438_Printer_Scott_s_iMac'
[ INFO    ] pibooth           : Generate the configuration file in '/home/pi/.config/pibooth/pibooth.cfg'
[ INFO    ] pibooth           : Generate the auto-startup file in '/home/pi/.config/autostart'
pi@raspberrypi:~ $ pibooth
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
pygame-menu 4.0.7
[ INFO    ] pibooth           : Installed plugins: 
[ INFO    ] pibooth           : Starting the photo booth application on Raspberry pi 4B
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (961) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1
[ INFO    ] pibooth           : Configuring OpenCV camera ...
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (1214) setProperty OpenCV | GStreamer warning: GStreamer: unhandled property
[ INFO    ] pibooth           : Connected to printer '438_Printer_Scott_s_iMac'
[ DEBUG   ] pibooth           : +< Activate state 'wait'
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'IHDR' 16 13
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'bKGD' 41 6
[ DEBUG   ] PIL.PngImagePlugin: |  b'bKGD' 41 6 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'pHYs' 59 9
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'tIME' 80 7
[ DEBUG   ] PIL.PngImagePlugin: |  b'tIME' 80 7 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'iTXt' 99 29
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'IDAT' 140 5756
[ DEBUG   ] pibooth           : +> took 4.146 seconds
[ DEBUG   ] pibooth           : +< Activate state 'choose'
[ INFO    ] pibooth           : |  Show picture choice (nothing selected)
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'IHDR' 16 13
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'iCCP' 41 388
[ DEBUG   ] PIL.PngImagePlugin: |  iCCP profile name b'ICC profile'
[ DEBUG   ] PIL.PngImagePlugin: |  Compression method 0
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'bKGD' 441 6
[ DEBUG   ] PIL.PngImagePlugin: |  b'bKGD' 441 6 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'pHYs' 459 9
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'tIME' 480 7
[ DEBUG   ] PIL.PngImagePlugin: |  b'tIME' 480 7 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'tEXt' 499 25
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'IDAT' 536 8192
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'IHDR' 16 13
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'iCCP' 41 388
[ DEBUG   ] PIL.PngImagePlugin: |  iCCP profile name b'ICC profile'
[ DEBUG   ] PIL.PngImagePlugin: |  Compression method 0
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'bKGD' 441 6
[ DEBUG   ] PIL.PngImagePlugin: |  b'bKGD' 441 6 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'pHYs' 459 9
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'tIME' 480 7
[ DEBUG   ] PIL.PngImagePlugin: |  b'tIME' 480 7 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'tEXt' 499 25
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'IDAT' 536 8192
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'IHDR' 16 13
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'bKGD' 41 6
[ DEBUG   ] PIL.PngImagePlugin: |  b'bKGD' 41 6 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'pHYs' 59 9
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'tIME' 80 7
[ DEBUG   ] PIL.PngImagePlugin: |  b'tIME' 80 7 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'iTXt' 99 29
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'IDAT' 140 5756
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'IHDR' 16 13
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'bKGD' 41 6
[ DEBUG   ] PIL.PngImagePlugin: |  b'bKGD' 41 6 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'pHYs' 59 9
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'tIME' 80 7
[ DEBUG   ] PIL.PngImagePlugin: |  b'tIME' 80 7 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'iTXt' 99 29
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'IDAT' 140 5756
[ DEBUG   ] pibooth           : +> took 2.572 seconds
[ DEBUG   ] pibooth           : +< Activate state 'chosen'
[ INFO    ] pibooth           : |  Show picture choice (1 captures selected)
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'IHDR' 16 13
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'iCCP' 41 388
[ DEBUG   ] PIL.PngImagePlugin: |  iCCP profile name b'ICC profile'
[ DEBUG   ] PIL.PngImagePlugin: |  Compression method 0
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'bKGD' 441 6
[ DEBUG   ] PIL.PngImagePlugin: |  b'bKGD' 441 6 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'pHYs' 459 9
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'tIME' 480 7
[ DEBUG   ] PIL.PngImagePlugin: |  b'tIME' 480 7 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'tEXt' 499 25
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'IDAT' 536 8192
[ DEBUG   ] pibooth           : +> took 4.377 seconds
[ DEBUG   ] pibooth           : +< Activate state 'preview'
[ INFO    ] pibooth           : |  Show preview before next capture
[ DEBUG   ] pibooth           : |  Add to buffer the image '3544134152'
[ DEBUG   ] pibooth           : |  No translation defined for 'en/capture' key
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'IHDR' 16 13
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'iCCP' 41 388
[ DEBUG   ] PIL.PngImagePlugin: |  iCCP profile name b'ICC profile'
[ DEBUG   ] PIL.PngImagePlugin: |  Compression method 0
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'bKGD' 441 6
[ DEBUG   ] PIL.PngImagePlugin: |  b'bKGD' 441 6 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'pHYs' 459 9
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'tIME' 480 7
[ DEBUG   ] PIL.PngImagePlugin: |  b'tIME' 480 7 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'tEXt' 499 25
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'IDAT' 536 8192
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'IHDR' 16 13
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'iCCP' 41 388
[ DEBUG   ] PIL.PngImagePlugin: |  iCCP profile name b'ICC profile'
[ DEBUG   ] PIL.PngImagePlugin: |  Compression method 0
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'bKGD' 441 6
[ DEBUG   ] PIL.PngImagePlugin: |  b'bKGD' 441 6 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'pHYs' 459 9
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'tIME' 480 7
[ DEBUG   ] PIL.PngImagePlugin: |  b'tIME' 480 7 (unknown)
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'tEXt' 499 25
[ DEBUG   ] PIL.PngImagePlugin: |  STREAM b'IDAT' 536 5653
[ DEBUG   ] pibooth           : |  Add to buffer the image '3547233200'
[ DEBUG   ] pibooth           : |  Add to buffer the image '3547233728'
[ DEBUG   ] pibooth           : |  Add to buffer the image '3547233512'
[ DEBUG   ] pibooth           : |  Add to buffer the image '3547233272'
[ DEBUG   ] pibooth           : |  Add to buffer the image '3547233728'
[ DEBUG   ] pibooth           : |  Add to buffer the image '3547233416'
[ DEBUG   ] pibooth           : |  Add to buffer the image '3547233272'
[ DEBUG   ] pibooth           : |  Add to buffer the image '3547233368'
[ DEBUG   ] pibooth           : +> took 4.527 seconds
[ DEBUG   ] pibooth           : +< Activate state 'capture'
[ INFO    ] pibooth           : |  Take a capture
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (1824) handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module v4l2src0 reported: Internal data stream error.
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (536) startPipeline OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (1085) setProperty OpenCV | GStreamer warning: no pipeline
[ DEBUG   ] pibooth           : |  Taking capture at resolution (1934, 2464)
[ ERROR   ] pibooth           : |  Can not capture frame
Traceback (most recent call last):
  File "/home/pi/pibooth/pibooth/booth.py", line 402, in main_loop
    self._machine.process(events)
  File "/home/pi/pibooth/pibooth/states.py", line 53, in process
    hook(cfg=self.cfg, app=self.app, win=self.win, events=events)
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_manager.py", line 457, in traced_hookexec
    return outcome.get_result()
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_result.py", line 114, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_result.py", line 76, in from_call
    result = func()
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_manager.py", line 454, in <lambda>
    lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_callers.py", line 113, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/local/lib/python3.9/dist-packages/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
  File "/home/pi/pibooth/pibooth/plugins/camera_plugin.py", line 103, in state_capture_do
    app.camera.capture(effect)
  File "/home/pi/pibooth/pibooth/camera/opencv.py", line 220, in capture
    raise IOError("Can not capture frame")
OSError: Can not capture frame
[ ERROR   ] pibooth           : |  system='Linux', node='raspberrypi', release='6.1.21-v8+', version='#1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023', machine='aarch64', processor=''
 ***********************************************************************************
 *                     Oops! It seems that pibooth has crached                     *
 *     You can report an issue on https://github.com/pibooth/pibooth/issues/new    *
 *                       and post the file: /tmp/pibooth.log                       *
 ***********************************************************************************
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (501) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
pi@raspberrypi:~ $ 

```
*** END OF LOGS ***

**Environment**
 - OS - Raspberry Pi OS
 - Camera - USB Webcam
 - Pibooth version 2.0.8

**Comment by anxuae** [comment]
pibooth not compatible with PiOS Bullseye (downgrade to Buster)
