### ISSUE TITLE
Raspberry Pi 4B - Pibooth does not launch / doesn't recognize Picamera v2

### ISSUE THREAD

**Issue by WOLJ** [pibooth/pibooth#577]
**Describe the bug**
Hello Everyone,

When I launch Pibooth, it says "no camera detected" but a Picamera V2 (8MP) is already well installed on my Raspberry Pi 4B.

Is there a conflict in the code between "lib camera" and "rpi camera" ?
And if this is the case, what should I do?

Thanks for your feedback.

**Steps to reproduce the bug**
1. Start Pibooth over console
2. Get no camera detected

**Logs**
pi@pi:~ $ source venv/bin/activate
(venv) pi@pi:~ $ pibooth
pygame 2.5.2 (SDL 2.28.3, Python 3.11.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
pygame-menu 4.0.7
/home/pi/venv/lib/python3.11/site-packages/gpiozero/devices.py:297: NativePinFactoryFallback: Falling back to the experimental pin factory NativeFactory because no other pin factory could be loaded. For best results, install RPi.GPIO or pigpio. See https://gpiozero.readthedocs.io/en/stable/api_pins.html for more information.
  warnings.warn(NativePinFactoryFallback(native_fallback_message))
[ INFO    ] pibooth           : Installed plugins: 
[ INFO    ] pibooth           : Starting the photo booth application on Raspberry pi 4B
/home/pi/venv/lib/python3.11/site-packages/pluggy/_manager.py:476: PluggyTeardownRaisedWarning: A plugin raised an exception during an old-style hookwrapper teardown.
Plugin: pibooth-core:camera, Hook: pibooth_setup_camera
OSError: Neither Raspberry Pi nor GPhoto2 nor OpenCV camera detected
For more information see https://pluggy.readthedocs.io/en/stable/api_reference.html#pluggy.PluggyTeardownRaisedWarning
  outcome = Result.from_call(
Traceback (most recent call last):
  File "/home/pi/venv/bin/pibooth", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/pi/venv/lib/python3.11/site-packages/pibooth/booth.py", line 490, in main
    app = PiApplication(config, plugin_manager)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/venv/lib/python3.11/site-packages/pibooth/booth.py", line 131, in __init__
    self.camera = self._pm.hook.pibooth_setup_camera(cfg=self._config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/venv/lib/python3.11/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/venv/lib/python3.11/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/venv/lib/python3.11/site-packages/pluggy/_manager.py", line 480, in traced_hookexec
    return outcome.get_result()
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/venv/lib/python3.11/site-packages/pluggy/_result.py", line 100, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/home/pi/venv/lib/python3.11/site-packages/pluggy/_result.py", line 62, in from_call
    result = func()
             ^^^^^^
  File "/home/pi/venv/lib/python3.11/site-packages/pluggy/_manager.py", line 477, in <lambda>
    lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/venv/lib/python3.11/site-packages/pluggy/_callers.py", line 156, in _multicall
    teardown[0].send(outcome)
  File "/home/pi/venv/lib/python3.11/site-packages/pibooth/plugins/camera_plugin.py", line 28, in pibooth_setup_camera
    cam = camera.find_camera()
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/venv/lib/python3.11/site-packages/pibooth/camera/__init__.py", line 52, in find_camera
    raise EnvironmentError("Neither Raspberry Pi nor GPhoto2 nor OpenCV camera detected")
**OSError: Neither Raspberry Pi nor GPhoto2 nor OpenCV camera detected**

**Environment**
 - OS : Raspberry Pi 4B 
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian

 - Pibooth : Pygame 2.5.2 (SDL 2.28.3, Python 3.11.2)
 - Camera : Picamera V2 - 8MP - IMX219

**Comment by werdeil** [comment]
Hi @WOLJ as stated in the [documentation](https://documentation.pibooth.org/en/latest/sources/install.html#software) pibooth is not yet compatible with OS above Buster (see #540).

Closing this issue
