### ISSUE TITLE
Resolution issue in hybrid mode – pibooth won't start if dslr resolution is bigger than pi max. pi hq cam resolution

### ISSUE THREAD

**Issue by lxne** [pibooth/pibooth#614]
**Describe the bug**
Hi, I am using pibooth in hybrid mode.
Preview is done with a Pi HQ Cam (max. 4056, 3040) and capture with a Nikon D5100.
The D5100 supports three resolutions S, M and L.
At first I tried to set L (4928, 3264) in pibooth config, but pibooth wouldn't start with this setting.
> "Invalid resolution requested: %r" % (value,))
> picamera.exc.PiCameraValueError: Invalid resolution requested: PiResolution(width=4928, height=3264)

If I use the Nikon's medium resolution (3696, 2448) and set it in config everything works fine.

**Steps to reproduce the bug**
1. use hybrid mode
2. set capture resolution higher than possible preview resolution
3. start pibooth
5. See error.

**Logs**

1. With `debug` mode set in the config
2.  Config file – Camera section
```
[CAMERA]
# Adjust ISO for lighting issues, can be different for preview and capture (list of integers accepted)
iso = 800

# Flip horizontally the capture
flip = False

# Rotation of the camera: 0, 90, 180 or 270, can be different for preview and capture (list of integers accepted)
rotation = 0

# Resolution for camera captures (preview will have same aspect ratio)
# PI HQ Cam max. 4056, 3040
# Nikon D5100 L 4928, 3264 M 3696, 2448
resolution = (4928, 3264)

# Delete captures from camera internal memory (when applicable)
delete_internal_memory = False
```
4. Logs from the console
```
pi@raspberrypi:~ $ pibooth
/usr/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: Your system is neon capable but pygame was not built with support for it. The performance of some of your blits could be adversely affected. Consider enabling compile time detection with environment variables like PYGAME_DETECT_AVX2=1 if you are compiling without cross compilation.
  return f(*args, **kwds)
pygame 2.6.0 (SDL 2.0.9, Python 3.7.3)
Hello from the pygame community. https://www.pygame.org/contribute.html
pygame-menu 4.0.7
[ INFO    ] pibooth           : Installed plugins: dropbox-0.0.3, google-photo-1.2.3, qr-download-0.1.2, qrcode-1.0.2, neopixel_spi_GRB-0.0.2
[ INFO    ] pibooth           : Starting the photo booth application on Raspberry pi 4B
[ INFO    ] pibooth           : Configuring hybrid camera (Picamera + gPhoto2) ...
Traceback (most recent call last):
  File "/usr/local/bin/pibooth", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/pibooth/booth.py", line 490, in main
    app = PiApplication(config, plugin_manager)
  File "/usr/local/lib/python3.7/dist-packages/pibooth/booth.py", line 131, in __init__
    self.camera = self._pm.hook.pibooth_setup_camera(cfg=self._config)
  File "/usr/local/lib/python3.7/dist-packages/pluggy/_hooks.py", line 433, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "/usr/local/lib/python3.7/dist-packages/pluggy/_manager.py", line 112, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/local/lib/python3.7/dist-packages/pluggy/_manager.py", line 418, in traced_hookexec
    return outcome.get_result()
  File "/usr/local/lib/python3.7/dist-packages/pluggy/_result.py", line 108, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/usr/local/lib/python3.7/dist-packages/pluggy/_result.py", line 70, in from_call
    result = func()
  File "/usr/local/lib/python3.7/dist-packages/pluggy/_manager.py", line 415, in <lambda>
    lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)
  File "/usr/local/lib/python3.7/dist-packages/pluggy/_callers.py", line 133, in _multicall
    teardown[0].send(outcome)
  File "/usr/local/lib/python3.7/dist-packages/pibooth/plugins/camera_plugin.py", line 34, in pibooth_setup_camera
    cfg.getboolean('CAMERA', 'delete_internal_memory'))
  File "/usr/local/lib/python3.7/dist-packages/pibooth/camera/hybrid.py", line 25, in initialize
    super(HybridRpiCamera, self).initialize(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pibooth/camera/base.py", line 42, in initialize
    self._specific_initialization()
  File "/usr/local/lib/python3.7/dist-packages/pibooth/camera/rpi.py", line 54, in _specific_initialization
    self._cam.resolution = self.resolution
  File "/usr/lib/python3/dist-packages/picamera/camera.py", line 2271, in _set_resolution
    "Invalid resolution requested: %r" % (value,))
picamera.exc.PiCameraValueError: Invalid resolution requested: PiResolution(width=4928, height=3264)
```

**Environment**
 - OS [Raspbian GNU/Linux 10 (buster)]
 - Camera [Pi High Quality camera + Nikon D5100]
 - Pibooth version [2.0.8]

**Comment by CiareCw455** [comment]
Hi, were you able to resolve this? I'd like to use a USB webcam for the preview and a Canon Powershot A640 to take the photo. Is this possible?
